
<div class="gog-copyright-bar">
    <div class="gog-copyright-bar-menu-row">

        <ul class="gog-copyright-bar-menue-links">
            <li><a href="#" ><?php echo __('About Us');?></a></li>
            <li><a href="#" ><?php echo __('Job Positions');?></a></li>
            <li><a href="#" ><?php echo __('Contact Us');?></a></li>
            <li><a href="#" ><?php echo __('Cooperation');?></a></li>

        </ul>
    </div>

    <div class="gog-copyright-bar-slogan">
        <ul>
            <li><a href="#" ><?php echo __('Copyright 2017');?></a></li>
        </ul>

    </div>

</div>