<div class="gog-info-bar">
    <div class="gog-info-bar-menu-row">
        <ul class="gog-info-bar-menu-links">
            <li><a href="#" ><i class="far fa-envelope"></i><?php echo __('info@gog.com');?></a></li>
            <li><a href="#" ><i class="fas fa-question-circle"></i><?php echo __('FAQs');?></a></li>
            <li><a href="#" ><?php echo __('Follow Orders');?></a></li>
            <li><a href="#" ><i class="fas fa-phone-square"></i><?php echo __('02132357744');?></a></li>


        </ul>
    </div>
</div>