
<div class="gog-subscribe-bar-menu">
    <div class="gog-subscribe-bar-menu-col">
        <a href="#" class="title" ><h3><span> <?php echo __('How To Put Order');?></span> </h3></a>
        <ul>
            <li><a href="#" ><?php echo __('How To Order');?></a></li>
            <li><a href="#" ><?php echo __('Shipment Methods');?></a></li>
            <li><a href="#" ><?php echo __('Payment Methods');?></a></li>
            <li><a href="#" ><?php echo __('About Us');?></a></li>

        </ul>

    </div>

    <div class="gog-subscribe-bar-menu-col">
        <a href="#" class="title" ><h3><span><?php echo __('Customers Services');?></span> </h3></a>
        <ul>
            <li><a href="#" ><?php echo __('FAQs');?></a></li>
            <li><a href="#" ><?php echo __('Orders And Returns');?></a></li>
            <li><a href="#" ><?php echo __('Privacy and Cookie Policy');?></a></li>
            <li><a href="#" ><?php echo __('Search Terms');?></a></li>
            <li><a href="#" ><?php echo __('Contact Us');?></a></li>
<!--            <li><a href="#" >li1</a></li>-->
<!--            <li><a href="#" >li2</a></li>-->
<!--            <li><a href="#" >li3</a></li>-->
<!--            <li><a href="#" >li4</a></li>-->
<!--            <li><a href="#" >li5</a></li>-->
        </ul>

    </div>

</div>