<?php
$dataHelper          = $this->helper('Gog\ImageSlider\Helper\Data');
$slides              = $block->getSlides();
$blockId             = rand().time();
$title               = $this->getConfig('title');
?>
<div class="block widget ves-widget imageslider-widget">
	<?php if($title){ ?>
	<div class="block-title">
		<strong><?php echo $title ?></strong>
	</div>
	<?php } ?>
	<div class="block-content image-slider-owl">
		<ul id="imageslider-<?php echo $blockId ?>"
		</ul>
    </div>

    <div class="owl-carousel owl-theme img-slider-blocks">
        <?php foreach ($slides as $k => $v) { ?>
            <div class="slider-block"><?php echo $v; ?></div>
        <?php } ?>
    </div>


</div>

<!--<div class="owl-carousel owl-theme">-->
<!---->
<!--    <div class="item"><h4>1</h4></div>-->
<!--    <div class="item"><h4>2</h4></div>-->
<!--    <div class="item"><h4>3</h4></div>-->
<!--    <div class="item"><h4>4</h4></div>-->
<!--    <div class="item"><h4>5</h4></div>-->
<!--    <div class="item"><h4>6</h4></div>-->
<!--    <div class="item"><h4>7</h4></div>-->
<!--    <div class="item"><h4>8</h4></div>-->
<!--    <div class="item"><h4>9</h4></div>-->
<!--    <div class="item"><h4>10</h4></div>-->
<!--    <div class="item"><h4>11</h4></div>-->
<!--    <div class="item"><h4>12</h4></div>-->
<!--    <div class="item"><h4>13</h4></div>-->
<!---->
<!--</div>-->



<!--<script type="text/javascript">-->
<!--    require(['jquery', 'slick'], function($){-->
<!--        $(function(){-->
<!--            $('.slick-carousel').slick-->
<!--            ({-->
<!---->
<!--            });-->
<!---->
<!--        });-->
<!--    });-->
<!--</script>-->

<script type="text/javascript" xml="space">// <![CDATA[
    require(['jquery', 'owlcarousel'], function() {
        jQuery(document).ready(function() {
            jQuery('.img-slider-blocks').owlCarousel({

                nav:true,
                autoplay:false,
                dots:true,
                margin:10,
                loop:true,
                items:1,
                navText : ["<div class='sliderarrow'><i class='fa fa-chevron-left'></i></div>","<div class='sliderarrow'><i class='fa fa-chevron-right'></i></div>"]


            });
            jQuery('.img-slider-blocks div').show();
        });
    });

    // ]]></script>