<?php
$dataHelper          = $this->helper('Gog\Advertisement\Helper\Data');
$Image              = $block->getImage();
$blockId             = rand().time();
$name               = $this->getConfig('name');
$pattern            = $this->getConfig('block_2');
?>
<!--<link rel="stylesheet" type="text/css" href='Gog\Advertisement\view\frontend\web\css\source\_module.less'>-->
<?php if($pattern=='Horizontal'){ ?>
<div class="block widget ves-widget Advertisment-widget">
 
    <?php if($name){ ?>
	<div class="block-title">
        <strong><?php echo $name ?></strong>
        
	</div>
	<?php } ?>
	
    
    <div class="Horiz">
        <?php foreach ($Image as $k => $v) { ?>
            <div class="Horizontal"><?php echo $v; ?></div>
        <?php } ?>
    </div>
   
    
</div>
<?php } ?>

<?php if($pattern=='Square'){ ?>
<div class="block widget ves-widget Advertisment-widget slider-block">
 
    <?php if($name){ ?>
	<div class="block-title">
        <strong><?php echo $name ?></strong>
        
	</div>
	<?php } ?>
	
   
    
    
   
    <div class="sq">
        <?php foreach ($Image as $k => $v) { ?>
            <div class="Square"><?php echo $v; ?></div>
        <?php } ?>
    </div>
   
</div>
<?php } ?>


